[package]
name = "rssatsnav"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.30.1"
dotenv = "0.15.0"
sha2 = "0.10.8"
secp256k1 = "0.27.0"
miniscript = "10.0.0"